"""add_trace_id_to_audit_and_jobs

Revision ID: d17f862cbb17
Revises: e0becf754b0a
Create Date: 2025-11-30 22:00:28.473925

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d17f862cbb17"
down_revision = "e0becf754b0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "trace_id",
                sa.String(length=36),
                nullable=True,
                comment="Trace ID for request tracking",
            )
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_trace_id"), ["trace_id"], unique=False)

    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trace_id", sa.String(), nullable=True))
        batch_op.alter_column(
            "parent_job_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )
        batch_op.create_index(batch_op.f("ix_background_jobs_trace_id"), ["trace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_background_jobs_trace_id"))
        batch_op.alter_column(
            "parent_job_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.drop_column("trace_id")

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_trace_id"))
        batch_op.drop_column("trace_id")

    # ### end Alembic commands ###
