"""add_background_jobs_table

Revision ID: e0becf754b0a
Revises: 393cd460e2a7
Create Date: 2025-11-30 19:55:54.345481

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e0becf754b0a"
down_revision = "393cd460e2a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_jobs",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("parent_job_id", sa.UUID(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["background_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_background_jobs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_background_jobs_message_id"), ["message_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_background_jobs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_background_jobs_task_name"), ["task_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_background_jobs_task_name"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_message_id"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_id"))

    op.drop_table("background_jobs")
    # ### end Alembic commands ###
