"""initial_audit

Revision ID: 393cd460e2a7
Revises: 548052531281
Create Date: 2025-11-30 17:31:36.033379

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "393cd460e2a7"
down_revision = "548052531281"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "actor_id",
            sa.String(length=255),
            nullable=True,
            comment="ID of the user who performed the action",
        ),
        sa.Column(
            "actor_email",
            sa.String(length=255),
            nullable=True,
            comment="Email of the user who performed the action",
        ),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
            comment="Action performed (CREATE, UPDATE, DELETE)",
        ),
        sa.Column(
            "target_model",
            sa.String(length=255),
            nullable=False,
            comment="Model path of the modified object (e.g. 'animals.Animal')",
        ),
        sa.Column(
            "target_object_id",
            sa.String(length=255),
            nullable=False,
            comment="ID of the modified object",
        ),
        sa.Column(
            "changes",
            sa.JSON(),
            nullable=False,
            comment="JSON diff of changes (before/after)",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address of the actor",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="User Agent string of the actor",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_logs_action", ["action"], unique=False)
        batch_op.create_index("ix_audit_logs_actor_email", ["actor_email"], unique=False)
        batch_op.create_index("ix_audit_logs_actor_id", ["actor_id"], unique=False)
        batch_op.create_index("ix_audit_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_audit_logs_target", ["target_model", "target_object_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_target")
        batch_op.drop_index(batch_op.f("ix_audit_logs_id"))
        batch_op.drop_index("ix_audit_logs_created_at")
        batch_op.drop_index("ix_audit_logs_actor_id")
        batch_op.drop_index("ix_audit_logs_actor_email")
        batch_op.drop_index("ix_audit_logs_action")

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
