[supervisord]
nodaemon=true
logfile=/var/log/supervisor/dramatiq_supervisord.log
pidfile=/var/log/supervisor/dramatiq_supervisord.pid
stdout_events_enabled=true

[program:dramatiq]
command=/app/deploy/shell_scripts/dramatiq_start.sh
directory=/app
process_name=dramatiq_%(process_num)02d
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/supervisor/dramatiq.log
stderr_logfile=/var/log/supervisor/dramatiq_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[supervisorctl]
serverurl=unix:///var/log/supervisor/supervisor.sock
