[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid
stdout_events_enabled=true  # Enable logging to the terminal

[program:uvicorn]
command=/app/deploy/shell_scripts/gunicorn_start.sh
directory=/app
process_name=gunicorn_%(process_num)02d
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/supervisor/uvicorn.log
stderr_logfile=/var/log/supervisor/gunicorn_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[supervisorctl]
serverurl=unix:///var/log/supervisor/supervisor.sock
