"""Initial database schema with all tables

Revision ID: 42ab7b48e86b
    Revises:
Create Date: 2025-10-06 20:24:57.621745

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "42ab7b48e86b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # =============================================================================
    # USERS TABLE - Core authentication and user management
    # =============================================================================
    # Remove this section if you don't need user authentication
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User's email address",
        ),
        sa.Column(
            "username", sa.String(length=50), nullable=False, comment="Unique username"
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Hashed password",
        ),
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            comment="User's first name",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            comment="User's last name",
        ),
        sa.Column("age", sa.Integer(), nullable=True, comment="User's age"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the user account is active",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Whether the user's email is verified",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="Whether the user has superuser privileges",
        ),
        sa.Column(
            "last_login",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the user last logged in",
        ),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for this record"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    # =============================================================================
    # ARTICLES TABLE - Content management system
    # =============================================================================
    # Remove this section if you don't need content management
    op.create_table(
        "articles",
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Title of the article",
        ),
        sa.Column(
            "content", sa.Text(), nullable=False, comment="Main content of the article"
        ),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for this record"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_articles_created_at"), "articles", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(op.f("ix_articles_title"), "articles", ["title"], unique=False)
    op.create_index(
        op.f("ix_articles_updated_at"), "articles", ["updated_at"], unique=False
    )

    # =============================================================================
    # SENSITIVE FIELDS TABLE - Data protection and privacy
    # =============================================================================
    # Remove this section if you don't need data protection features
    op.create_table(
        "sensitive_fields",
        sa.Column(
            "field_name",
            sa.String(length=255),
            nullable=False,
            comment="Field name or pattern to match",
        ),
        sa.Column(
            "is_exact_match",
            sa.Boolean(),
            nullable=False,
            comment="True for exact match, False for regex pattern",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether this pattern is active",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of what this field contains",
        ),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for this record"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensitive_fields_created_at"),
        "sensitive_fields",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sensitive_fields_field_name"),
        "sensitive_fields",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sensitive_fields_id"), "sensitive_fields", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sensitive_fields_updated_at"),
        "sensitive_fields",
        ["updated_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables in reverse order (sensitive_fields -> articles -> users)
    op.drop_index(op.f("ix_sensitive_fields_updated_at"), table_name="sensitive_fields")
    op.drop_index(op.f("ix_sensitive_fields_id"), table_name="sensitive_fields")
    op.drop_index(op.f("ix_sensitive_fields_field_name"), table_name="sensitive_fields")
    op.drop_index(op.f("ix_sensitive_fields_created_at"), table_name="sensitive_fields")
    op.drop_table("sensitive_fields")

    op.drop_index(op.f("ix_articles_updated_at"), table_name="articles")
    op.drop_index(op.f("ix_articles_title"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_created_at"), table_name="articles")
    op.drop_table("articles")

    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")

    # ### end Alembic commands ###
