"""init with uuid ids

Revision ID: 4f35e18d
Revises:
Create Date: 2025-10-01 19:25:39.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f35e18d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(op.f("ix_articles_title"), "articles", ["title"], unique=False)
    op.create_table(
        "sensitive_fields",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "field_name",
            sa.String(length=255),
            nullable=False,
            comment="Field name or pattern to match",
        ),
        sa.Column(
            "is_exact_match",
            sa.Boolean(),
            nullable=True,
            comment="True for exact match, False for regex pattern",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
            comment="Whether this pattern is active",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of what this field contains",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="When this pattern was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="When this pattern was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensitive_fields_field_name"),
        "sensitive_fields",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sensitive_fields_id"), "sensitive_fields", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensitive_fields_id"), table_name="sensitive_fields")
    op.drop_index(op.f("ix_sensitive_fields_field_name"), table_name="sensitive_fields")
    op.drop_table("sensitive_fields")
    op.drop_index(op.f("ix_articles_title"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
