"""fix_users_uuid_column_type

Revision ID: 8aed20b7993d
Revises: 4abcc6b81598
Create Date: 2025-10-01 20:38:21.262387

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8aed20b7993d"
down_revision = "4abcc6b81598"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert the users.id column from sa.UUID() to postgresql.UUID(as_uuid=True)
    # This ensures consistency with other tables that use PostgreSQL UUID type

    # First, we need to alter the column type
    # Since we're just changing the column type specification (not the actual data),
    # we can use a simple alter operation
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to sa.UUID() if needed
    op.alter_column(
        "users",
        "id",
        existing_type=postgresql.UUID(as_uuid=True),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
