"""add sensitive_fields table for dynamic masking configuration

Revision ID: 9287fd46dd18
Revises: ab4314ae4cfe
Create Date: 2025-10-01 18:23:20.321029

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9287fd46dd18'
down_revision = 'ab4314ae4cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False, comment='Field name or pattern to match'),
    sa.Column('is_exact_match', sa.Boolean(), nullable=True, comment='True for exact match, False for regex pattern'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this pattern is active'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of what this field contains'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When this pattern was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When this pattern was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensitive_fields_field_name'), 'sensitive_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_sensitive_fields_id'), 'sensitive_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensitive_fields_id'), table_name='sensitive_fields')
    op.drop_index(op.f('ix_sensitive_fields_field_name'), table_name='sensitive_fields')
    op.drop_table('sensitive_fields')
    # ### end Alembic commands ###

