"""init

Revision ID: ab4314ae4cfe
Revises: 83b8d6000d97
Create Date: 2025-09-19 18:36:06.178437

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4314ae4cfe'
down_revision = '83b8d6000d97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

